# Name of your application. Used to uniquely configure containers.
service: upic-custom-uploader

# Name of the container image.
image: tealight/upic-custom-uploader

# Deploy to these servers.
servers:
  web:
    - 37.221.193.95
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption. 
proxy: 
  ssl: true
  host: upic.netcup.gifts
  # Proxy connects to your container on port 80 by default.
  app_port: 3000

# Credentials for your image host. s
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  server: registry.eu-central-1.aliyuncs.com
  username: tealight

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  remote: ssh://root@registry.tealight.uk
